INSERT INTO ROLES(NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES(NAME) VALUES ('ROLE_CUSTOMER');
INSERT INTO USERS(USERNAME,PASSWORD,EMAIL) VALUES ('NANDHINI KUMARAN','$2a$10$uumYAcHkwnEgG6dMmVpupeIA5Jn7JN7xAWBsvcwSacziyiPd14AlC','nandhuu.nandy@gmail.com');
INSERT INTO USERS_ROLES(USER_ID,ROLE_ID) VALUES (1,1);