INSERT INTO CREDIT_ACCOUNT (APPLICANT_NAME, TOTAL_LIMIT, CURRENCY,START_DATE,END_DATE,TOTAL_LIMIT_HOME,TOTAL_LIMIT_CAR) VALUES ('Nandhini', 1000000, 'SGD','2022-09-24','2024-09-24',50000,20000);
INSERT INTO ROLES(NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES(NAME) VALUES ('ROLE_CUSTOMER');
INSERT INTO USERS(USERNAME,PASSWORD,EMAIL) VALUES ('NANDHINI KUMARAN','$2a$10$uumYAcHkwnEgG6dMmVpupeIA5Jn7JN7xAWBsvcwSacziyiPd14AlC','nandhuu.nandy@gmail.com');
INSERT INTO USERS_ROLES(USER_ID,ROLE_ID) VALUES (1,1);